python evaluate_pope.py \
    --gpu 5 \
    --base_model_dir "/mnt/shared/shared_hf_home/hub/models--Qwen--Qwen3-VL-8B-Instruct" \
    --lora_vqa_attn_dir "/mnt/arc/mjojic/causal-patch-selection/training/lora_v4_attn_align" \
    --pope_cache_dir "/mnt/shared/shared_hf_home/datasets" \
    --start_idx 6000 \
    --end_idx 6300 \
    --num_samples_sc 1 \
    --max_tokens 1024 \
    --gpu_memory_utilization 0.5 \
    --max_model_len 8192 \
    --output_json "./pope_eval_results/pope_results_lora_v4_attn_align.json" \
    --eval_base
